### ISSUE TITLE
Weird error

### ISSUE THREAD

**Issue by KalifZerich** [braeven/FS22_A_ProductionRevamp#12] opened 2023-11-06 15:51 UTC
Hello out of nowhere game show me this error

2023-11-06 16:48 Error: Running LUA method 'mouseEvent'.
dataS/scripts/gui/InGameMenuProductionFrame.lua(197) : attempt to index local 'production' (a nil value)
2023-11-06 16:48 Error: Running LUA method 'update'.
D:/FS22_MODS/FS22_A_ProductionRevamp/scripts/revamp_recipeDisplay.lua:561: attempt to index local 'production' (a nil value)
2023-11-06 16:48 Error: Running LUA method 'update'.
dataS/scripts/gui/elements/SmoothListElement.lua(707) : attempt to compare nil with number
2023-11-06 16:48 Error: Running LUA method 'update'.

It happens with all productions (ingame too), I don't go to that menu immediately after buying them.

No new scripted mods.

Thanks

**Comment by Achimobil** [comment] 2023-11-07 07:11
First we always need the full log file. When on server both log files.
Additionally if we could not reproduce the error, we could not do anything. But first. The log please

**Comment by braeven** [comment] 2024-07-25 16:36
I will close this, please open a new ticket, if this error happens again

**Closed as completed by braeven** 2024-07-25 16:36 UTC
